/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'i309511' at '4/18/15 2:28 AM' with Gradle 2.2.1
 *
 * @author i309511, @date 4/18/15 2:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
